### ISSUE TITLE
Regarding usage of wxPython on Windows 10

### ISSUE THREAD

**Issue by sparshgarg23** [udacity/nd013-c2-fusion-exercises#1]
So,I tried cloning the repository and tried running the code under MTT
However on execution I recieved the following error
C++ assertion "strcmp(setlocale(0, 0), "C") == 0" failed at ..\..\src\common\intl.cpp(1694) in wxLocale::GetInfo(): You probably called setlocale() directly instead of using wxLocale and now there is a mismatch between C/C++ and Windows locale.
Things are going to break, please only change locale by creating wxLocale objects to avoid this!
My python version is 3.8.5 and wxPython is the recent version
Any ideas on how to resolve this issue?

**Comment by sparshgarg23** [comment]
It seems the way to resolve this is  listed here
import locale
locale.setlocale(locale.LC_ALL, 'C')
These lines need to be added in the file backend_wx.py located in
anaconda3/Lib/site-packages/matplotlib/backends

**Comment by UAnjali** [comment]
Hi @sparshgarg23,
Thank you for the suggestion. Maybe you can raise a PR for the same if the issue still exists.
Happy Learning
